### ISSUE TITLE
Add a thermostat tile for controlling heating/cooling

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#2]
From @jamesP;

So if we have a thermostat tile I would think it would be nice to have temperature, mode and fan speed settings. Not all devices are going to support all modes so being able to filter those will be useful eg auto, heat, cool, dry, fan etc. Being able to set the steps and range of the temperature setting and possibly the fan speed range would be helpful. I know some units have different temperature ranges for different modes as well. Having on tile feedback of at least the mode and temperature setting as well as the state will be useful. Potentially being able to display the target temperature and possibly target humidity (not sure if that is a thing with dry mode) and the actual temperature and humidity on tile would be nice but potentially difficult with the tile size and may look to cluttered. Maybe needs to focus on the settings rather than showing actual and targets. Possibly utilising a modal screen for the setting choices to allow for a more minimalist tile displaying the current settings. Just ideas for the discussion.

**Comment by moinmoin-sh** [comment]
With all the proposals above it doesn't look easy to create a pop-up that would fit all requirements. A lot of config options would be necessary.

Wouldn't it be possible to set up customized HVAC linked screens with the tile types we have?

Our available tile styles could be used
- `on tile selector` with style `buttonUpDown `and cmnd/ `selectorList `to make 1 out of n selection (off, low, middle, high) or (cool, off, heat) 
- style `buttonLevel `for temperature settings
- style `indicator `to show current temp / humidity 
- ...

**Comment by sumnerboy12** [comment]
Yep you definitely could. But a half round temp picker/gauge in a model popup, colored from blue to red would be nice for a thermostat tile. The tile itself could then show setpoint temp and actual temp.  Click to launch the popup.

Maybe call it a `setpoint` tile?

There other mode stuff could be in a separate tile as you suggest.

**Comment by sumnerboy12** [comment]
Something like this...

![image](https://user-images.githubusercontent.com/5060842/185713595-83d720bd-2ea7-4b6f-8253-2bf55e59e25c.png)

**Comment by moinmoin-sh** [comment]
The HA style.

Just thinking about "super tiles" that span over multiple tiles  like `2 hor`, `2 vert`, `2x2` . Could offer new ideas for screen layouts.
Any thoughts?

**Comment by sumnerboy12** [comment]
I think they would be very useful. But I think in this case you could get away with a model popup for the setpoint temp gauge and the base tile just shows current and setpoint temps?

I would be interested to see what other super tiles you have in mind tho...

**Comment by moinmoin-sh** [comment]
Short term the pop-up is the right way to go.

possible screen layout with super tile : 
top  a 2x2 super tile with the above settings tile
BL selector tile for ventilation speed
BR indicator for outside conditions

weather forecast for the next hours/days on a 2 vert (landscape) super tille

horizontal / vertical on screen sliders 

No idea how usefull that would be?

**Comment by sumnerboy12** [comment]
Yeah I'm not sure either. I can see how sliders or volume controls in larger tiles, i.e. 1x tile for up, 1x tile for down, could be useful in some scenarios. But that could be done with a new tile style of simply up or down.

Will have more of a think about it.
