### ISSUE TITLE
Hung at the Logo screen if wifi network is not available at boot

### ISSUE THREAD

**Issue by plains203** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#22]
If your configured wifi network is not available when the screen boots it will sit at the logo screen indefinitely. This is an undesirable behavior for in wall mounted screens because there is no easy way to reboot them. 
Proposal is that the screen reboots on a 5 minute no connection timeout. This would only need to be configured if the wifi settings have been set to connect to an AP but probably would be ok even if it hasn't?

**Comment by sumnerboy12** [comment]
Moved to https://github.com/OXRS-IO/OXRS-IO-WT32-ESP32-LIB/issues/5
