### ISSUE TITLE
set tile to offline / online

### ISSUE THREAD

**Issue by austinscreations** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#23]
I've been working on rebuilding @sumnerboy12 led controller sub flow to allow more control from multiple interfaces. something that both HA and NR have is the ability to set an element to an offline state so you can't click or activate it. think this may be potentially useful on the screen. 

my other thought i just to use teh sub label to display offline state, and ignore the messages but wonder if something better would feel nicer overall.

**Comment by moinmoin-sh** [comment]
I suggest we "grey out" the tile and disable touch sensitivity so no clicks are generated. The tile would still be able to show all state information.

**Comment by moinmoin-sh** [comment]
proposal with tile 3(on state)  and tile 4 (off state) disabled

![grafik](https://user-images.githubusercontent.com/53935853/188326606-7303f849-3d69-4438-a127-af24e31bc6a9.png)

**Comment by sumnerboy12** [comment]
That looks good to me Moin. Pretty clear and obvious.

**Comment by austinscreations** [comment]
looks / sounds good to me
