### ISSUE TITLE
Ability to display plain text or HTML on a screen

### ISSUE THREAD

**Issue by hazymat** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#25]
In addition to being able to display tiles / keypads etc., would be useful to be able to display plain text or even HTML on a screen.

Useful for serving latest news / weather...

**Comment by sumnerboy12** [comment]
I was thinking this would be a new tile style, which shows a label/icon/summary on the tile and when clicked launches a fullscreen popup where you can fill it with text/HTML/markup.

**Comment by hazymat** [comment]
That would be even better than what I said!

**Comment by moinmoin-sh** [comment]
Rendering anything else than plain text is an issue here. LVGL doesn't offer any format changes within a label widget (basically a text box). The only formating options are "\n" for a line break and the recoloring as we use it for the textIcon and that doesn't work across line breaks.

**Comment by caitken-com** [comment]
Even without what @moinmoin-sh just said about unable to format text, remembering that html requires a massive parser. Doubt you could get one to work on an ESP.
Best bet would have been a sub-set of Mark-Down.

**Comment by moinmoin-sh** [comment]
Given the constaints we have there will be no chance to parse and display any standard mark-up text. To show anything other than plain text a FW specific formating has to done by the backend.
As an alternative to plain text the information could be presented in a "feed style" like pop-up.
Each "feed" has a `heading `and a `body`. Character based coloring is possible.
Could look like this
![grafik](https://user-images.githubusercontent.com/53935853/188492120-1fd8d17e-2296-4a56-bb01-bf241d792c2b.png)

**Comment by sumnerboy12** [comment]
That looks pretty cool I think Moin, should be able to do plenty with those tools.
