### ISSUE TITLE
Simplify colorPicker tiles

### ISSUE THREAD

**Issue by MakerDockio** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#36]
Can we have a single colorPicker tile style with a mode property:

mode: “rgb” | “cct” | “rgbCct” 

The tile style payloads are pretty similar and seems daft to have all three individual styles.

If mode is set to cct || rgbCct we can include the temperature tab and the kelvin stuff.

We can also set a default for mode as rgbCct so it always renders.

This will greatly simplify things especially the docs.

**Comment by sumnerboy12** [comment]
As discussed, this was done mainly to keep the configuration schema simple - adding a new `mode` option which is only applicable to colour picker tiles would pollute the admin UI when configuring non-colour picker stuff.

Not a great reason I'll admit, but using the style to differentiate isn't all that bad and it seems to fit logically in the docs as well.
