### ISSUE TITLE
Add support for WT32-SC01-PLUS?

### ISSUE THREAD

**Issue by shmrymbd** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#48]
Do you have any plan in future?

**Comment by sumnerboy12** [comment]
@austinscreations has one of these but unfortunately it is lacking the necessary PSRAM size so isn't capable of running this firmware. It is a real shame as his testing shows it is a far superior screen.

**Comment by moinmoin-sh** [comment]
@shmrymbd FYI  V 2.0.0 of the FW has been released. It has a built that runs on the WT32-SC01-PLUS
