### ISSUE TITLE
Empty dropdown list causes a reboot, tested on 86s

### ISSUE THREAD

**Issue by smcgann99** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#75]
Sorry but it looks like I found another issue -  this payload causes a reboot - {
    "tiles": [
        {
            "screen": 1,
            "tile": 7,
            "dropDownList": []
        }
    ]
}

**Comment by moinmoin-sh** [comment]
Yes, that's a bug. The FW should be able to handle this correctly (at least no reboot).

Out of curiosity, what was the reason for sending the empty payload?
