### ISSUE TITLE
Enhancement: tile that opens a popup with slider(s) for level control

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#82]
a tile `style `like we have for the color picker but shows slider(s) for level control

**Comment by smcgann99** [comment]
That sounds useful, I have written code for controlling WLED which has lots of values to be set.

**Comment by moinmoin-sh** [comment]
Such screen can be configured using the customizable screen layout (number of rows/columns) and tile panning..
No need for an extra pop-up

**Comment by moinmoin-sh** [comment]
Not needed
