### ISSUE TITLE
Enhancement: add userData to tile event payload

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#83]
see discussion on Discord:

https://discord.com/channels/1008489838565134416/1008492060636094616/1167231202122547291

https://discord.com/channels/1008489838565134416/1008492060636094616/1167365346865463326

**Comment by sumnerboy12** [comment]
Another option for the field name could be `tag`, instead of `userData`.
